# Generated by Django 4.2 on 2025-02-27 05:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField(max_length=25)),
                ('funct', models.TextField(max_length=25)),
                ('file', models.TextField(max_length=50)),
                ('error_type', models.TextField()),
                ('error', models.TextField()),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_entered_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Error_log',
            },
        ),
    ]
